### ISSUE TITLE
Temperature Sensors not Appearing

### ISSUE THREAD

**Issue by Grubs** [ozczecho/custom_components#1]
I have 2 of the temperature sensors and they don't seem to be appearing in the entities for the Integration in HA.

I can see the climate entity and one for each of my zones all ok.

**Comment by ozczecho** [comment]
Hi @Grubs - If you hit the api direct from a browser (url: http://localhost:5353/api/aircons - don't forget to change the url to meet your setup) do you see your sensors? 

![image](https://user-images.githubusercontent.com/18643617/106273407-ba8eea00-6286-11eb-8a0d-0a5d6ab96ade.png)

If yes, then try re-adding the integration into HA. All you have to do is delete it and re-add. If the sensors exist they should be picked up.

**Comment by Grubs** [comment]
Hi @ozczecho - Mine appears a little differnet than yours

Mainly the "zoneTemperatureType": 0,

ID 0 = AirTouch Rooms
ID 2 & 4 = Sensor Rooms

Any idea if I can change the type to 1 like yours?

{
  "aircons": [
    {
      "id": 8,
      "airTouchId": "58******",
      "mode": 4,
      "name": "Paul",
      "powerStatus": 0,
      "status": "OK",
      "brandId": 0,
      "touchPadGroupId": 1,
      "touchPadTemperature": 24,
      "desiredTemperature": 23,
      "roomTemperature": 22,
      "fanMode": 1,
      "zones": [
        {
          "id": 0,
          "name": "Dining",
          "status": 1,
          "fanValue": 0,
          "isSpill": false,
          "zoneTemperatureType": 2,
          "sensors": []
        },
        {
          "id": 1,
          "name": "Lounge",
          "status": 1,
          "fanValue": 100,
          "isSpill": false,
          "zoneTemperatureType": 0,
          "sensors": []
        },
        {
          "id": 2,
          "name": "S*****",
          "status": 1,
          "fanValue": 0,
          "isSpill": false,
          "zoneTemperatureType": 0,
          "sensors": [
            {
              "id": 4,
              "isAvailable": true,
              "isLowBattery": false,
              "temperature": 22
            }
          ]
        },
        {
          "id": 3,
          "name": "Master  ",
          "status": 1,
          "fanValue": 60,
          "isSpill": false,
          "zoneTemperatureType": 0,
          "sensors": []
        },
        {
          "id": 4,
          "name": "Z*****",
          "status": 1,
          "fanValue": 0,
          "isSpill": false,
          "zoneTemperatureType": 0,
          "sensors": [
            {
              "id": 8,
              "isAvailable": true,
              "isLowBattery": false,
              "temperature": 22
            }
          ]
        },
        {
          "id": 5,
          "name": "Garage",
          "status": 0,
          "fanValue": 0,
          "isSpill": false,
          "zoneTemperatureType": 0,
          "sensors": []
        }
      ],

**Comment by Grubs** [comment]
![image](https://user-images.githubusercontent.com/10626257/106343293-91a53e00-62f4-11eb-87a7-17606da5cdad.png)

I see it shows the type 0 there too

**Comment by ozczecho** [comment]
@Grubs - I think I spotted the issue. If you pull down the latest version of the api (https://github.com/ozczecho/vzduch-dotek) it should fix this. Remember you may need to reload the integration to add the newly discovered sensors (there is a reload option - so it may work).

**Comment by Grubs** [comment]
I'm 99% sure I've done it all ok. But can't see anything changed my end.

![image](https://user-images.githubusercontent.com/10626257/106353189-a4d9fd00-6338-11eb-9d55-641a97fb1607.png)

I believe I rebuilt the docker image too & stopped and started it again. Also tried recreate in Portainer.

![image](https://user-images.githubusercontent.com/10626257/106353194-b28f8280-6338-11eb-9712-a3534ad2bbc7.png)

![image](https://user-images.githubusercontent.com/10626257/106353264-2d589d80-6339-11eb-8166-3861ae8026a2.png)

I then deleted the HA integration and re-added it

![image](https://user-images.githubusercontent.com/10626257/106353239-f71b1e00-6338-11eb-81fe-c65bd7712a38.png)

Have I missed something?

**Comment by ozczecho** [comment]
@Grubs - Can you show me the json doc returned from http://localhost:5353/api/aircons - then I can see if its been updated and if the values have changed.

**Comment by Grubs** [comment]
Here it is:

{
  "aircons": [
    {
      "id": 8,
      "airTouchId": "58*****",
      "mode": 3,
      "name": "Paul",
      "powerStatus": 1,
      "status": "OK",
      "brandId": 0,
      "touchPadGroupId": 1,
      "touchPadTemperature": 21,
      "desiredTemperature": 22,
      "roomTemperature": 23,
      "thermostatMode": 0,
      "fanMode": 1,
      "zones": [
        {
          "id": 0,
          "name": "Dining",
          "status": 1,
          "fanValue": 0,
          "isSpill": false,
          "desiredTemperature": 23,
          "zoneTemperatureType": 2,
          "sensors": []
        },
        {
          "id": 1,
          "name": "Lounge",
          "status": 1,
          "fanValue": 100,
          "isSpill": false,
          "desiredTemperature": 25,
          "zoneTemperatureType": 0,
          "sensors": []
        },
        {
          "id": 2,
          "name": "Z*****",
          "status": 1,
          "fanValue": 0,
          "isSpill": false,
          "desiredTemperature": 23,
          "zoneTemperatureType": 1,
          "sensors": [
            {
              "id": 4,
              "isAvailable": true,
              "isLowBattery": false,
              "temperature": 23
            }
          ]
        },
        {
          "id": 3,
          "name": "Bedroom",
          "status": 1,
          "fanValue": 100,
          "isSpill": false,
          "desiredTemperature": 20,
          "zoneTemperatureType": 0,
          "sensors": []
        },
        {
          "id": 4,
          "name": "S*****",
          "status": 1,
          "fanValue": 0,
          "isSpill": false,
          "desiredTemperature": 24,
          "zoneTemperatureType": 1,
          "sensors": [
            {
              "id": 8,
              "isAvailable": true,
              "isLowBattery": false,
              "temperature": 23
            }
          ]
        },
        {
          "id": 5,
          "name": "Garage",
          "status": 0,
          "fanValue": 0,
          "isSpill": false,
          "desiredTemperature": 0,
          "zoneTemperatureType": 0,
          "sensors": []
        }
      ],

**Comment by Grubs** [comment]
![76AD3C0D-C2B0-41EB-BD7B-00C2FC69FB1D](https://user-images.githubusercontent.com/10626257/106355948-6ac62680-634b-11eb-865b-341ea47d9b4c.jpeg)
I can see this has changed to 1 actually

**Comment by ozczecho** [comment]
Do you see the sensors on the integration page (the 2nd entry in the screenshot below)

![image](https://user-images.githubusercontent.com/18643617/106370864-654ff700-63b2-11eb-81d9-0602f8822f6e.png)

**Comment by Grubs** [comment]
Nah I don’t. That’s what I’m finding quite odd. I just see these 7 entities 

![B63B60A9-BC81-422F-8926-72D0817B3826](https://user-images.githubusercontent.com/10626257/106372371-d09fc600-63be-11eb-849a-919db89f548e.jpeg)

**Comment by ozczecho** [comment]
Hmm ok...to go further need more info. Next step would be to delete the integration and then set the logging level to `debug` for the `airtouch3 custom component`. And paste the relevant log entries here.

**Comment by Grubs** [comment]
Sorry @ozczecho I must be blind. Where am I enabling debug mode for the custom component. 

Also I tried deleting, rebooting HA, adding again. That didn’t help either

**Comment by ozczecho** [comment]
@Grubs - in your configuration.yaml file there should be a logger section. 

```
logger:
  default: info
  logs:
    custom_components.airtouch3: debug
```

**Comment by Grubs** [comment]
Thanks. Log attached

[add-integration-debug.log](https://github.com/ozczecho/custom_components/files/5901125/add-integration-debug.log)

**Comment by ozczecho** [comment]
@Grubs - Looks like there was an issue how the temperature sensors were being added. I believe I have fixed the issue. You will need to pull down the latest `custom_component\airtouch3` code...namely file `vzduch.py`.

**Comment by Grubs** [comment]
Success!

![image](https://user-images.githubusercontent.com/10626257/106558597-f1f5e300-6573-11eb-9d89-c08bc33cfa66.png)


On a side note. How exactly should my configuration.yaml be configured

If I have only have "**airtouch3:**" I get this error:

![image](https://user-images.githubusercontent.com/10626257/106558436-a3e0df80-6573-11eb-84e5-080f89efea82.png)

If I change it to this it loads ok

![image](https://user-images.githubusercontent.com/10626257/106558451-ae02de00-6573-11eb-9aaa-603da1a9e5c3.png)

**Comment by ozczecho** [comment]
@Grubs - Excellent. Thanks for testing. Feel free to remove the debug statement from your config.

re: `How exactly should my configuration.yaml be configured` - you don't need to add `airtouch3` to your `configuration.yaml` - the integration is fully handled via the UI config tool.
