### ISSUE TITLE
device_state_attributes errors in logs

### ISSUE THREAD

**Issue by lilhater** [ozczecho/custom_components#3]
I get the following error in Home Assistant's logs when starting up:

Entity switch.living (<class 'custom_components.airtouch3.switch.ZoneSwitch'>) implements device_state_attributes. Please report it to the custom component author.

A quick google search suggests this requires a rename: https://community.home-assistant.io/t/warning-that-custom-component-is-using-device-state-attributes/376020

**Comment by ozczecho** [comment]
@lilhater - Thanks for letting me know. I am on 2021.10. I will try and upgrade over the weekend and update the component.

**Comment by lilhater** [comment]
Hi @ozczecho, I should be the one thanking you for such an amazing custom component. 
It's been great replacement to the official AirTouch 3 app which often loses connectivity or logs me out permanently.

I forgot to mention that I'm using Home Assistant 2021.12.10 in Docker.

**Comment by ozczecho** [comment]
@lilhater - No worries.Like you I was pretty frustrated that the only way I could add my AC to my home automation was via IFTTT. While IFTTT does "work" there were a lot of short comings and hence my motivation to remove IFTTT from the equation. Now I solely rely on Home Assistant to control my AC....

Happy 2022.
